name: Publish to NPMJS

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - uses: actions/setup-node@v4
        name: Setup node
        with:
          node-version: 20
          cache: pnpm
      - name: Install package dependencies
        run: pnpm install --frozen-lockfile
      - name: Run unit tests
        run: pnpm run test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: pnpm
      - name: Get Package Version from Tag
        run: echo "VERSION=$(echo $GITHUB_REF_NAME | sed -e "s/^v//")" >> $GITHUB_ENV
      - name: Update package version in control file
        run: sed -i -e "s/{{VERSION}}/$VERSION/g" package.json
      - name: Install package dependencies
        run: pnpm install --frozen-lockfile
      - name: Publish package
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH}}
